apriltags:
  tag_0:
    id: 0
    size: 0.24
    position:
      x: -4.53
      y: 0.0
      z: 1.0
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: 1.57
      
  tag_1:
    id: 1
    size: 0.24
    position:
      x: -4.53
      y: -2.5
      z: 0.5
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: 1.57

  tag_2:
    id: 2
    size: 0.24
    position:
      x: -2.5
      y: -4.827
      z: 1.0
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: -3.14

  tag_3:
    id: 3
    size: 0.24
    position:
      x: 0.0
      y: -4.827
      z: 0.5
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: -3.14

  tag_4:
    id: 4
    size: 0.24
    position:
      x: 2.30
      y: -6.0
      z: 1.0
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: 1.57

  tag_5:
    id: 5
    size: 0.24
    position:
      x: 5.0
      y: -6.5
      z: 1.25
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: -1.57


  tag_6:
    id: 6
    size: 0.24
    position:
      x: 7.0
      y: -4.834
      z: 0.75
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: -3.14
  
  tag_7:
    id: 7
    size: 0.24
    position:
      x: 8.6
      y: -4.0
      z: 1.1
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: -1.57


  tag_8:
    id: 8
    size: 0.24
    position:
      x: 7.0
      y: -2.43
      z: 1.0
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: 0.0

  tag_9:
    id: 9
    size: 0.24
    position:
      x: 5.0
      y: -1.8
      z: 1.0
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: -1.57

  tag_10:
    id: 10
    size: 0.24
    position:
      x: 5.0
      y: -0.6
      z: 1.1
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: -1.57

  tag_11:
    id: 11
    size: 0.24
    position:
      x: 3.5
      y: -0.07
      z: 1.0
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: 0.0

  tag_12:
    id: 12
    size: 0.24
    position:
      x: 1.90
      y: 1.0
      z: 1.1
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: -1.57

  tag_13:
    id: 13
    size: 0.24
    position:
      x: 0.5
      y: 2.29
      z: 1.0
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: 0.0

  tag_14:
    id: 14
    size: 0.24
    position:
      x: -1.5
      y: 2.29
      z: 1.1
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: 0.0

  tag_15:
    id: 15
    size: 0.24
    position:
      x: -3.0
      y: 2.29
      z: 1.0
    orientation:
      roll: 1.57
      pitch: 0.0
      yaw: 0.0