<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>moveit_commander</name>
  <version>0.1.0</version>
  <description>C++ ROS2 node wrapping MoveIt2 MoveGroupInterface. Subscribes to joint/pose/gripper commands and executes them via MoveIt2 planning.</description>
  <maintainer email="bachala_rajesh@outlook.com">Bachala Rajesh</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>project_interfaces</depend>
  <depend>std_msgs</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
<!-- This package was generated using the Turtle Nest ROS 2 package creator -->
