generated: '2025-11-24T16:19:26.123075'
shoulder_pan:
  range_min: 889
  range_max: 3359
  homing_offset: 2124
shoulder_lift:
  range_min: 882
  range_max: 3248
  homing_offset: 2065
elbow_flex:
  range_min: 867
  range_max: 3075
  homing_offset: 1971
wrist_flex:
  range_min: 837
  range_max: 3186
  homing_offset: 2011
wrist_roll:
  range_min: 52
  range_max: 3870
  homing_offset: 1961
gripper:
  range_min: 2046
  range_max: 3485
  homing_offset: 2100
