/**:
    ros__parameters:
      tag_family: tag36h11
      edge_length: 0.24     #tag edge length (bloack corner to black corner on an edged. (units in meters)
      nthreads: 1
      quad_decimate: 1.0
      quad_sigma: 1.0
      refine_edges: 1
      decode_sharpening: 0.15

      global_tags_location_filename: sim_apriltags_global_location_gazebo_world.yaml

