<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>calibration_and_setup</name>
  <version>0.1.0</version>
  <description>One-off servo setup and calibration scripts for the SO-101 arm (set motor IDs, set home offsets, set return level).</description>
  <maintainer email="bachala_rajesh@outlook.com">Bachala Rajesh</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
