joints:
  shoulder_pan:
    id: 1
    homing_offset: 1965
    range_min: 997
    range_max: 3366

  shoulder_lift:
    id: 2
    homing_offset: -1423
    range_min: 898
    range_max: 3020

  elbow_flex:
    id: 3
    homing_offset: -1692
    range_min: 1062
    range_max: 3036

  wrist_flex:
    id: 4
    homing_offset: -1718
    range_min: 990
    range_max: 2900

  wrist_roll:
    id: 5
    homing_offset: 1783
    range_min: 260
    range_max: 3940

  gripper:
    id: 6
    homing_offset: 1402
    range_min: 2046
    range_max: 3072
