/**:
  ros__parameters:
    parent_frame: "leader_base_link"
    child_frame: "leader_gripper_link"
    record_frequency: 50

    emotions:
      - "happy"
      - "sad"
      - "angry"
      - "fearful"
      - "surprised"
      - "neutral"
      - "curious"
      - "excited"
      - "tired"
      - "stressed"
      - "relaxed"
      - "initial"


    
    
    motion_dir: "motion_recordings"
    num_joints: 6
    record_frequency: 50